### ISSUE TITLE
Mailchimp form

### ISSUE THREAD

**Issue by brashrebel** [realbig/TH_MULLINS_HVAC#12]
We'll be needing a form on the home page and in the sidebar on subpages that says "Subscribe to our newsletter and be entered in our monthly drawing for a free tune up". This will subscribe users to a Mailchimp list. There will also be a discreet link below the form to the terms of the drawing which will be a page on the site containing text from the client.

**Comment by brashrebel** [comment]
Just invited you to the Mailchimp account. Let me know if you need anything further to integrate a form into the site. I'm something strong on the home page and then in sub pages sidebars. Do what you can to make it look nice, professional, unobtrusive and inviting. Tasteful color and placement possibly with an icon. Use the text above for the time being.

**Comment by d4mation** [comment]
I activated the MailChimp WordPress plugin that was available on the MultiSite network and after attempting to log in using my credentials, it returned this error in JSON. It looks like I don't have the necessarily permissions within MailChimp to use it.

`{"result":"error","response":"an error occurred: API keys belonging to users with \"manager\" roles are not permitted to access helper\/account-details"}`

**Comment by brashrebel** [comment]
I just upgraded your privileges.

**Comment by d4mation** [comment]
Currently the "Terms and Conditions" link goes nowhere. Once we have it on the Site we can easily change its URL.

There were virtually no Filters/Hooks for me to utilize, so I made a manual installation of the Widget which gave me a bit more control, but not perfect control, of the DOM Structure. I'm not sure how I feel about the Mail Icon...
