### ISSUE TITLE
Highlight services on home page

### ISSUE THREAD

**Issue by brashrebel** [realbig/TH_MULLINS_HVAC#19]
There are 5 main services provided by the client:
- Heating
- Air Conditioning
- Geo Thermal
- Refrigeration
- Indoor Air Quality

I'd like to see us highlight those on the home page below the main CTA area. I'm envisioning some kind of simple grid with each services as a square or rectangle button with text and an icon. There should be a corresponding page for each (content will be obtained from the client later). Make all 5 empty pages and make them children of a Services page which contains an elegant list of button links to each of the 5 services.

You might have to find some icon library or something. I love using icomoon and I think @joelworsham knows of some others. Ask questions here if you have them.

**Comment by joelworsham** [comment]
Font awesome for the win!

Also, something to consider: http://stackoverflow.com/questions/11135261/should-i-use-i-tag-for-icons-instead-of-span

**Comment by d4mation** [comment]
I'm considering using [Weather Icons](https://erikflowers.github.io/weather-icons/) in addition to Font Awesome since a few of the Services could benefit from slightly better icons. Looking at `wi-strong-wind` and `wi-snowflake-cold` in particular.

Yeah, I agree to be honest. I've just been seeing more and more people using `<i>` instead of `<span>` lately. I'll swap them over to `<span>`s.

**Comment by joelworsham** [comment]
Oh those are nice! Font Awesome is great, but it does seem to be lacking some basic icons... Although I suppose no icon pack can truly cover **everything**.

As for the `<i>`'s vs `<span>`'s, really it's the developers call. There's arguments for both sides. I just figured I'd bring it up as food for thought. My personal preference is `<span>` ;)

**Comment by d4mation** [comment]
I changed up the Services buttons on the Home Page and Services page in an attempt to make them look a bit nicer.
- "Rebalanced" the grid items so the larger ones are on top.
- Added Gutters
- Re-ordered so Heating and Air were first, followed alphabetically with the rest
