### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by brashrebel** [realbig/TH_MULLINS_HVAC#20]
Please add Tim's bio to the about page. Then add headers with both the owners names above their respective bios and include a picture of Tim next to his bio. You can find a picture of Tim on mounthopecommunitychurch.com.

**Comment by d4mation** [comment]
Added his Bio. Decided to handle this via the Content Editor as it seemed to make the most sense. Do we have a photo for Sharon?

**Comment by brashrebel** [comment]
I have no photo yet for Shannon but have requested one.
