### ISSUE TITLE
Change domain

### ISSUE THREAD

**Issue by brashrebel** [realbig/TH_MULLINS_HVAC#23]
We're switching from mullinsheatandair.com to mullinsheatingandairllc.com. I'm pointing the domains now.

**Comment by d4mation** [comment]
Ping is showing me a different IP than the other sites on the Multisite, so I will check in on this again later on things have propagated.

As for right now, it is showing a Database Connection Error. I tried changing the relevant Domain in the wp-config file to match the changed Domain and it didn't seem to change anything.

![image](https://cloud.githubusercontent.com/assets/7770631/11065439/6fc07f32-8791-11e5-9312-b66df80bef7f.png)

**Comment by brashrebel** [comment]
Yeah, I might need to point the old domain back there so you can change the mapping settings. Let me do that.

**Comment by brashrebel** [comment]
Try again soon.

**Comment by d4mation** [comment]
Tried again and got to the Domain Mapping screen within wp-admin.

Couldn't add a Domain, so I tried removing the old one thinking I could then add the new one afterward. That turned out to be a bad idea and now it is stuck in a redirect loop.

**Comment by brashrebel** [comment]
Ummm....shoot.

**Comment by d4mation** [comment]
It seems the Redirect Loop is fixed, but now both domains lead to the WP Engine 404 screen. The one for when the domain is pointing right, but hasn't been mapped.

I'm not sure how to handle that with this current setup. Normally I'd map the domains by logging in to WP Engine.

**Comment by brashrebel** [comment]
I just took care of it. It is a little complicated how this works but it is done now.
