### ISSUE TITLE
Broken images in header and slider

### ISSUE THREAD

**Issue by brashrebel** [realbig/TH_MULLINS_HVAC#34]
Can we somehow get the images back in? They're broken in the testimonial feature and in the Dependability Promise thingy.

**Comment by d4mation** [comment]
I'm working on the Dependability Promise ones right now.

For the Testimonials, they will just need to be assigned Featured Images.
I'll take care of that in a minute.

**Comment by d4mation** [comment]
As per #36, we are dropping the CTA. Once #36 is done, the broken images for the Dependability Promise will be gone.

Testimonial Images have been set to the same ones I had in my local environment. They are changed via the Featured Image of each Testimonial.
